export const SITE_NAME = 'Sample Blog';
export const SITE_DESCRIPTION = 'A statically generated blog example using Next.js and WordPress';
export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL;
export const API_URL = process.env.NEXT_PUBLIC_API_URL;
export const WORDPRESS_PREVIEW_SECRET = process.env.NEXT_PUBLIC_WORDPRESS_PREVIEW_SECRET;
export const COOKIES_TOKEN_NAME = 'wpt';
export const COOKIES_PAGED_NAME = 'pgd';
export const API_USERNAME = process.env.NEXT_PUBLIC_API_USERNAME;
export const API_PASSWORD = process.env.NEXT_PUBLIC_API_PASSWORD;
